before_install:
  - gem update --system
  - gem install bundler
  - psql -c "CREATE USER superliga WITH PASSWORD 'password';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON  DATABASE superliga_development to superliga;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON  DATABASE superliga_test to superliga;" -U postgres

language: ruby
rvm:
  - 2.6.1
script:
  - bundle exec rake db:create db:migrate
  - bundle exec rspec
