before_install:
  - gem update --system
  - gem install bundler
  - psql -c "CREATE USER superliga WITH PASSWORD 'password';" -U postgres
language: ruby
rvm:
  - 2.6.1
script:
  - bundle exec rake db:create db:migrate
  - bundle exec rspec
